### ISSUE TITLE
Line break for layer titles in TOC

### ISSUE THREAD

**Issue by MarkusKonk** [GeoNode/geonode-mapstore-client#1264]
Currently, layer titles are not shown completely but cut ("This is a long layer titl..."). The entire title is only visible in a tooltip triggered by a mouse-over.

<img src="https://user-images.githubusercontent.com/2863409/198002251-0776187d-a219-4c0e-b1a0-026e47d8d189.png" width=30% height=30%>

It might be better to show the entire title using a line break in the TOC window. 

<img src="https://user-images.githubusercontent.com/2863409/198002597-e0b2398e-79c0-4cdd-9910-18fb3b078927.png" width=30% height=30%>

This change might result in an obsolete tooltip.
I think there are two options:
Option 1 (preferred): Change styling in the code of the mapstore core and remove the tooltip ([link to where changes are needed](https://github.com/geosolutions-it/MapStore2/blob/a1a792ffb6c7c7ddab45bc8f7ac2f4b9a18b617c/web/client/components/TOC/fragments/Title.jsx#L54)).

Option 2: Change style of component via an extension (plugin) outside the maptsore core. I tried it in an [initial unfinished quick-and-dirty implementation](https://github.com/MarkusKonk/geonode-mapstore-client/blob/lineBreaker/geonode_mapstore_client/client/js/plugins/LayerTitleTocLineBreaker.jsx), but I am not very happy with it.

**Comment by gannebamm** [comment]
@giohappy @allyoucanmap please evaluate the stated options

**Comment by t-book** [comment]
+1 for Opition 2.

**Comment by francbartoli** [comment]
+1 for option 2

**Comment by giohappy** [comment]
I also think that the typical and expected behavior is the current one. 
A different visualization should be managed as a custom implementation out of core, so Option 2.

**Comment by allyoucanmap** [comment]
@gannebamm @giohappy @MarkusKonk here you can find two solutions that can be applied to the css to change the style of the cards

## Single line title fill all available space

This solution ensures that the title fill all the available space then add the ellipsis if needed. (cc @giohappy probably this fix need to be ported on geonode-mapstore-client less theme)

- lesscss rules
```less
#mapstore-drawermenu {
    .mapstore-toc {
        .toc-default-layer-head {
            display: flex;
            .toc-title {
                flex: 1;
                min-width: auto;
                max-width: none;
                width: auto;
                &:hover {
                    font-weight: inherit;
                }
            }
        }
        .toc-default-group-head {
            display: flex;
            > div {
                flex: 1;
                display: flex;
                max-width: calc(100% - 40px);
                .toc-group-title {
                    flex: 1;
                    min-width: auto;
                    max-width: none;
                    width: auto;
                    &:hover {
                        font-weight: inherit;
                    }
                }
            }
        }
    }
}
```

- compiled css

```css
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head {
  display: flex;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head .toc-title {
  flex: 1;
  min-width: auto;
  max-width: none;
  width: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head .toc-title:hover {
  font-weight: inherit;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head {
  display: flex;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div {
  flex: 1;
  display: flex;
  max-width: calc(100% - 40px);
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div .toc-group-title {
  flex: 1;
  min-width: auto;
  max-width: none;
  width: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div .toc-group-title:hover {
  font-weight: inherit;
}
```
- preview
![image](https://user-images.githubusercontent.com/19175505/202414226-e9dff4f3-4412-44a3-a398-bdb1c75f7d32.png)

## Multiple line title fill all available space

This other solution should allows the title to be displayed on multiple lines that could be applied as custom style in a geonode project.

- lesscss rules
```less
#mapstore-drawermenu {
    .mapstore-toc {

        .toc-default-layer-head {
            display: flex;
            .toc-title {
                flex: 1;
                min-width: auto;
                max-width: none;
                width: auto;
                &:hover {
                    font-weight: inherit;
                }
            }
        }
        .toc-default-group-head {
            display: flex;
            > div {
                flex: 1;
                display: flex;
                max-width: calc(100% - 40px);
                .toc-group-title {
                    flex: 1;
                    min-width: auto;
                    max-width: none;
                    width: auto;
                    &:hover {
                        font-weight: inherit;
                    }
                }
            }
        }

        // display title on multiple lines
        .toc-default-layer-head {
            min-height: 40px;
            height: auto;
            .toc-title {
                word-break: break-all;
                overflow: visible;
                white-space: inherit;
                height: auto;
            }
        }
        .toc-default-group-head {
            min-height: 40px;
            height: auto;
            > div {
                .toc-group-title {
                    word-break: break-all;
                    overflow: visible;
                    white-space: inherit;
                    height: auto;
                }
            }
        }
    }
}
```
- compiled css
```css
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head {
  display: flex;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head .toc-title {
  flex: 1;
  min-width: auto;
  max-width: none;
  width: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head .toc-title:hover {
  font-weight: inherit;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head {
  display: flex;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div {
  flex: 1;
  display: flex;
  max-width: calc(100% - 40px);
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div .toc-group-title {
  flex: 1;
  min-width: auto;
  max-width: none;
  width: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div .toc-group-title:hover {
  font-weight: inherit;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head {
  min-height: 40px;
  height: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-layer-head .toc-title {
  word-break: break-all;
  overflow: visible;
  white-space: inherit;
  height: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head {
  min-height: 40px;
  height: auto;
}
.msgapi #mapstore-drawermenu .mapstore-toc .toc-default-group-head > div .toc-group-title {
  word-break: break-all;
  overflow: visible;
  white-space: inherit;
  height: auto;
}
```
- preview
![image](https://user-images.githubusercontent.com/19175505/202413984-87592ae3-f6b4-4de5-9b91-bb7cb50e5afd.png)
