### ISSUE TITLE
Cannot dev on geonode-mapstore-client along a docker install

### ISSUE THREAD

**Issue by syldor** [GeoNode/geonode-mapstore-client#1495]
I have a full docker installation of geonode on localhost.

How to use this instance with `geonode-mapstore-client` to dev locally ? 

Compilation is fine on `mapstore` side but then it does not find the geonode instance:

```
[HPM] Error occurred while trying to proxy request / from localhost:8081 to http://localhost:8000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:8081 to http://localhost:8000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/4158062/a4d42d9a-7e89-4a4d-9303-5f446657dcbf)

I tried to open the ports 8000:8000 in docker-compose of `genode-project` but not luck:

```
  django:
    <<: *default-common-django
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django4${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}

        ' --output /dev/null http://127.0.0.1:8001/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10
    environment:
      - IS_CELERY=False
    ports:
      - "8000:8000"
    entrypoint: [ "/usr/src/urban_gis_geonode/entrypoint.sh" ]
    command: "uwsgi --ini /usr/src/urban_gis_geonode/uwsgi.ini"
```

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/4158062/da13a17a-99a4-4222-8c8b-b4b2a5fca284)

Is there a way to do ?
