### ISSUE TITLE
Improvements to the layout of the action bar menus

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1536]
1. Reduce to spacgin between buttons 
  ```css
 .msgapi .gn-menu .gn-menu-list>li>* {
       margin-right: 0.2rem;
   }
```
2. Add the `fa-caret-down` icon to dropdown menus
3. Remove the vertical separator
4. Move the "Delete" button to the end

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/efea1853-ced9-475f-a731-69c7fe104133)
